### ISSUE TITLE
Double show

### ISSUE THREAD

**Issue by aymericdo** [bbonch/vue3-recaptcha2#1]
Good job !

However, there is a typo in the props.. You wrote two times "show"  so the component is expected a number for the show props 😄

**Comment by repcsi** [comment]
Yep, got the same issue:
`[Vue warn]: Invalid prop: type check failed for prop "show". Expected Number, got Boolean with value false. 
  at <VueRecaptcha siteKey="won_t_show_my_key" show=false size="normal"  ... > 
  at <EventRegistration> 
  at <App>`

**Comment by FosterHangdaan** [comment]
I'm guessing that the second `show` is supposed to be the `tabindex` prop. `tabindex` is passed to `grecaptcha.render` but it's not defined.

**Comment by bbonch** [comment]
I will fix. Thanks!
