### ISSUE TITLE
Not Working with VUE CDN?

### ISSUE THREAD

**Issue by jobdiogenes** [bbonch/vue3-recaptcha2#10]
Hello, 

I try to  use  in codepen.io 

But, no success. 

I try in two ways. 
1) Using import  [Demo vue3-recaptcha2 cnd](https://codepen.io/jobdiogenes/pen/rNYNpqX)
2) Embedded module [vue3-recaptcha2 embedded](https://codepen.io/jobdiogenes/pen/qBVWPaP)

Whats is wrong? Or work only with node?

Thanks

Job

**Comment by bbonch** [comment]
Hi,
CDN version does not work yet. Embedded does.
I fixed your pen [vue3-recaptcha2 embedded](https://codepen.io/bbonch/pen/zYpwxzv)
Thanks

**Comment by jobdiogenes** [comment]
> Hi, CDN version does not work yet. Embedded does. I fixed your pen [vue3-recaptcha2 embedded](https://codepen.io/bbonch/pen/zYpwxzv) Thanks

Great,

Thanks very much.
