### ISSUE TITLE
Recaptcha div added to HTML is not removed

### ISSUE THREAD

**Issue by harikvpy** [bbonch/vue3-recaptcha2#6]
I observe that for every instantiation of the component, there's a <div visibility="hidden"> add to the app HTML at the bottom. Rightfully this should be removed when the page where captcha component is unmounted.

This is a sample screenshot of this div:
![image](https://user-images.githubusercontent.com/6202401/127942296-15865b47-e00b-43fb-a320-cb57cc93e4c9.png)

Looking at your code, this element seems to be created by Google's captcha JS. Perhaps there's a call that you need to make to remove this element during component unmount.

**Comment by bbonch** [comment]
I think v-if is not a good example. There is no built-in way to destroy recaptcha. You should use v-show and reset.
